### ISSUE TITLE
Huge thanks and words of gratitude, not an issue actually :)

### ISSUE THREAD

**Issue by Ne0niq** [mwilsnd/SkyrimSE-SmoothCam#1]
Hi mwilsnd!

I can not be silent after google accidentally gave me a link to this github page, so please let me say a couple of thank words!
Sorry for posting here, in Issues section, I just don't know how to contact with you and where you published your work except github.

I am very grateful for what you are doing! Thank you soooo much!

I case if you open for suggestions, I would like to see separate camera behavior modifiers:
CombatRanged
CombatMagic
Combat Melee
HorsebackCombatRanged (should include Magic too)
HorsebackCombatMelee.
These modifiers may be handy for many players who want, for example, a steady camera during shooting using a bow or casting spells.

3D crosshair is very bold idea! ;) I am dreamed of it during development of my [mod](https://www.nexusmods.com/skyrimspecialedition/mods/18524), but it's impossible to achieve that using Papyrus scripts only. Oh, it will very hard to make it work as intended, since everyone is using different skeletons and animations affecting the angle and point of projectiles flight. But please don't give up! :) You doing good!

Wish you luck and the best things in your life, so that you will finish this project and give it long and glorious life!

Regards, NeOniq.

**Comment by mwilsnd** [comment]
Thanks for the encouraging words! I'll definitely look into adding those extra offset options.
This mod has required a fair amount of reverse engineering to get to this point (especially the raycasting), so I haven't had much time to actually play with the camera mechanics. This mod is living here while I iterate and improve on it before publishing it on the nexus, whenever that might be. And yeah the 3D crosshair is going to be a challenge, the game seems to simply hard code everything else assuming the crosshair is at the center of the screen making things fun.

**Comment by qudix** [comment]
I took a look at the source and I wanted to ask whether you would benefit from using the CommonLib library: https://github.com/Ryan-rsm-McKenzie/CommonLibSSE

**Comment by mwilsnd** [comment]
Perhaps, appears they've certainly dismantled a lot of the game. Pretty much all the RE work I needed to do has been finished already though, but If I ever find myself needing something from it I'll for sure pick it up.
