### ISSUE TITLE
Swimming/Sneaking settings are using the same values

### ISSUE THREAD

**Issue by WasabiIceCream** [mwilsnd/SkyrimSE-SmoothCam#10]
I've only tried changing the values in the MCM, and not the .json itself yet.
The Swimming and Sneaking values are shared, and only the sneaking values work.
Swimming cam doesn't work at all. Changing values in the Swimming menu just changes for Sneaking.

EDIT: Swimming settings work if you directly set them in the .json itself. It'll get reset to Sneaking values if you mess around in the MCM, though.

Thanks for the best camera mod for Skyrim.

**Comment by mwilsnd** [comment]
Seems like I made a copy-paste error in the MCM script, I've made the corrections and uploaded a new release with the fix for you.

**Comment by WasabiIceCream** [comment]
Solved.
