### ISSUE TITLE
Entering and leaving map with "Patch HUD" enabled teleports my character.

### ISSUE THREAD

**Issue by StoneColb** [mwilsnd/SkyrimSE-SmoothCam#11]
I figured this would be easier to explain through video, so I recorded a quick one to show what's happening:

[Video Here](https://drive.google.com/file/d/1E2nh-hw2Mb2OkOMkqGuCqdzfvlNvyD6N/view?usp=sharing)

**Comment by mwilsnd** [comment]
That is incredible haha. I'll try and get to the bottom of this,

**Comment by mwilsnd** [comment]
Can I ask what mods you are using? While I'm unable to replicate this in a vanilla game with just SKSE and the camera, I have an idea of what might be going on. There might be a mod you have which is causing the camera to continue updating while the map is open. Being able to replicate it would better enable me to make a patch for it.

**Comment by StoneColb** [comment]
I can't upload my Modwatch for some reason, but I think I know what mod it might be.

[This one](https://www.nexusmods.com/skyrimspecialedition/mods/27859)

**Comment by mwilsnd** [comment]
Yup, that is the culprit. I've added a simple check to ensure the HUD patch doesn't do its thing in the map menu. I'll publish a new release later with the patch, currently trying to fix shadow maps not getting the correct camera data and looking a bit broken.

**Comment by StoneColb** [comment]
Dope.

While we're here. Ever considered having presets? Would be neat to have different camera settings available as a save/load function

**Comment by mwilsnd** [comment]
I've just published alpha 1.3 which fixes the HUD issue once and for all, ended up finding the correct way to do what I was trying to hack around originally. Presets are a great idea, not sure why I didn't think to do them already. I'll work on that for the next version.

**Comment by StoneColb** [comment]
Dope
