### ISSUE TITLE
3rd-Person Camera Aiming is Way Off

### ISSUE THREAD

**Issue by WasabiIceCream** [mwilsnd/SkyrimSE-SmoothCam#12]
So, kinda hard to explain, but I'll try my best. I've tested this using both Alpha 1.1 and Alpha 1.3. Same results. I've isolated this mod to be the only cause.

When my character is in 3rd-person, and weapons are sheathed, my aiming is just completely off. I have to look to the extreme left of whatever I'm trying to interact with in order to pick up, or use.
But, when I unsheathe a weapon, the aiming is mostly fine, but might still be a bit off. I should note that, I did edit in my own 3D Crosshair into the SkyHUD files, but this occurs even on the default hudmenu.swf included with SmoothCam.

I did some thorough testing, and found that this is only an issue for FEMALE characters... Any Male character seems to be perfectly fine.

I've attached some screenshots. They're of me looking at the absolute point where the activation triggers for the Tanning Rack at Warmaiden's. First with weapon sheathed, second with weapon in hand. Both screens are using the same exact offset settings (0 side, 40 up to see above my character's head).

![ScreenShot124](https://user-images.githubusercontent.com/12481327/82116510-92c31a80-9727-11ea-834b-b0f139b84c5d.png)

![ScreenShot126](https://user-images.githubusercontent.com/12481327/82116519-a9697180-9727-11ea-8a0a-a24c281e43a2.png)

Thanks!

**Comment by mwilsnd** [comment]
The normal crosshair being wrong is expected, though a major difference between male and female characters is not. I've gone ahead and added an option to always use the 3D crosshair which should help.

**Comment by WasabiIceCream** [comment]
Doesn't seem to help at all. Still have to look far to the left when aiming when sheathed.

Also, my SkyHUD crosshair seems to just be gone now, both in first and third-person, regardless of the 3D crosshair settings. The crosshair included with SmoothCam works, but still has the problem with female characters.

No idea if anyone else is experiencing this issue, but like I said, I totally isolated this mod, and it's definitely this.
Starting a new game, SmoothCam doesn't activate until you save and load once. The problem doesn't exist until I save, load, and the mod activates itself.
Weird that it's only affecting females.

Thanks!

**Comment by mwilsnd** [comment]
I see what the issue is now - The game doesn't know about the new camera position when updating whatever happens to be under the crosshair. I'll look in to different methods to try and feed the new camera position to whatever part of the game manages the crosshair stuff. It is interesting seeing the game use a different source for the raycast when not in a combat stance.

**Comment by derickso** [comment]
I also don't get SmoothCam loaded until saving and reloading

**Comment by derickso** [comment]
How to make SkyHUD compatible now that HUDMenu.as has changed? I guess have to try and add Crosshair3D script to SkyHUD's hudmenu.swf? EDIT: Hm, doesn't seem to be a way to add scripts with JPEXS Decompiler

**Comment by mwilsnd** [comment]
Alright I managed to fix this, and as a nice side effect the 3D crosshair got a lot better. The normal crosshair is good enough now for pretty much everything except archery and magic so I've slimmed down those redundant options. I did have to reverse engineer the physics update code for projectiles in order to get everything playing nice with each other which was a bit of a pain to figure out, but whatever.

@derickso Yeah, to add support for the crosshair to another mod you'll need flash CS4 or CS5 unfortunately. The crosshair is now its own element, not grouped with the rest of the HUD. I did upload the flash project inside the UI folder for people to look at when adding support to their own mods.

**Comment by WasabiIceCream** [comment]
@mwilsnd  On the topic of the HUD... Doesn't this change make SmoothCam extremely incompatible with pretty much everything except the included HUD? At least in regards to the 3D Crosshair features. Most mod authors I've asked seem totally uninterested in adding compatibility themselves, but it was easy enough to add the required lines using the JPEXS Decompiler. When it comes to Adobe Flash, I'm not sure if its possible to even obtain CS4 or CS5 anymore, and trying the latest Animator trial, I don't know my asshole from my elbow.

I'm not used to working with Flash, but this doesn't seem like something that's as easy to fix from a user's point, especially since these are paid applications.

Either way, the aiming is fixed, and that's what was most important. XD
Thanks again.

**Comment by derickso** [comment]
Well technically the main purpose of this mod is just to change the smoothiness of the third person camera and a raycasting crosshair isn't strictly necessary for that, but it is unfortunate that this is the price of fixing the crosshair.

I've obtained CS4/6 by extraneous means *cough* but unfortunately SkyHUD doesn't have its source files anywhere. I've asked the author but he responds about once every two months.

**Comment by mwilsnd** [comment]
After a bit of messing around I figured out how the scaleform interface works a bit more, to the point now where I'm able to manipulate the crosshair without shipping a custom hudmenu file. I've published a new release, give it a try with your custom hud and see if it all works - so long as the asset names in the swf are the same the new system should just work.

**Comment by WasabiIceCream** [comment]
This is an exciting piece of progress!
Doesn't seem to be working for my crosshair, though (SkyHUD).
Figure I'll just attach it here, I guess. From what I can tell, mine might be a more slightly updated version (Updated for use with the Survival Mode update) than what's been included with SmoothCam before. No idea if that matters, though.

[Wasabihudmenu.zip](https://github.com/mwilsnd/SkyrimSE-SmoothCam/files/4671682/Wasabihudmenu.zip)

**Comment by mwilsnd** [comment]
I installed skyhud and tried that out on its own, appeared to work. Then I tried your version of the hudmenu file and it still seemed to work. I know it loaded your version as the stamina meter looked different. I wonder if you have some option set in the skyhud config file causing the crosshair position to be changed after smoothcam tries to set it? Attached a picture of the game running with your version of the hudmenu file with the camera built in debug mode to visualize the crosshair trace.
![image](https://user-images.githubusercontent.com/53413200/82731578-a1807300-9ccd-11ea-8e7d-1e8e70569852.jpg)

If you can't figure out what might be wrong, I can make a special build for you with some debug logging to see if it is finding the crosshair correctly and have it dump position data for it every frame.

**Comment by WasabiIceCream** [comment]
I'll mess around with the SkyHUD settings, and see if something in there is doing it.
Gonna close this issue for now, since the original issue is solved.
Thanks!

**Comment by derickso** [comment]
Getting incorrect projectile locations after firing with 3d crosshair enabled + SkyHUD

**With 3D**
![01](https://user-images.githubusercontent.com/6112623/82741892-0fe42600-9d0c-11ea-8137-22806e17c4da.jpg)

**Without 3D**
![02](https://user-images.githubusercontent.com/6112623/82741893-0fe42600-9d0c-11ea-9c0b-0bcf790f6913.jpg)

**Comment by derickso** [comment]
Raycasting seems fine when readying spells/bow, but once fired the trajectory is completely off, and the crosshair jumps after firing
