### ISSUE TITLE
minCameraFollowDistance, combatOffset, combatzoomOffset

### ISSUE THREAD

**Issue by ghost** [mwilsnd/SkyrimSE-SmoothCam#14]
Firstly, really great mod and I'm almost sold on switching to this and endorsing it on /r/skyrimmods as an alternative to other camera mods, but there's a couple of features I'd like to see added/tweaked before I fully migrate from 3PCO and the like.

_minCameraFollowDistance_
I would appreciate a higher range for this, as with my current camera mod the camera follow distance in 3rd person is 160 units, which greatly complements my want for a souls-like experience in Skyrim.

_combatOffset_
Sort of a quality-of-life tweak I'd love to see is a global edit for the offset of up/side for all combat value offsets.

**combatzoomOffset**
This is not yet a parameter that is available, but this is more of a suggestion. I've seen that the mod allows for camera position offsets while in combat, but does not yet allow the camera to zoom out/in by a fixed amount upon entering combat.

Again, thank you so much for your work, it was really nice to check back on this one day and see the glaring issue of hud mod incompatibility was solved. Hoping to see further progress in the future!

**Comment by mwilsnd** [comment]
I've upped the slider range for follow distance to 256, should be enough, I've also added a new group edit tab so you can edit common settings for different offset groups all at once now. Zoom offsets were pretty much the last thing missing from offset groups so I went ahead and added those too. Let me know if you have any issues with the new options.
