### ISSUE TITLE
Crosshair Position is Incorrect For Ultrawide Resolutions

### ISSUE THREAD

**Issue by WasabiIceCream** [mwilsnd/SkyrimSE-SmoothCam#17]
![oudSXWB](https://user-images.githubusercontent.com/12481327/83965002-cb10d100-a86d-11ea-9202-1e86ad9ab867.jpg)

This is 3440x1440 resolution

**Comment by mwilsnd** [comment]
This should be fixed now in alpha 1.7, if not let me know and I'll take another look at it.
