### ISSUE TITLE
Not compatible with the lock-on camera in Poser Hotkeys Plus

### ISSUE THREAD

**Issue by as996656503** [mwilsnd/SkyrimSE-SmoothCam#18]
It seems to cause the lock-on camera function to fail

**Comment by ouoertheo** [comment]
Came here to say the same. SmoothCam makes my game so much better but poser hotkeys grudgingly wins.

**Comment by mwilsnd** [comment]
I don't really have the time to investigate this myself, however if anyone wants to take a look at it and submit a pull request I'd be happy to take a look. Closing this for now.
