### ISSUE TITLE
Shoulder Swap Hotkey?

### ISSUE THREAD

**Issue by shwowsh** [mwilsnd/SkyrimSE-SmoothCam#19]
`Works` great, and the huge amount of customization is the golden standard for a mod. Also works perfect with a controller, which is not always the case with camera mods.

What about a key to swap sides along the X axis? Like a shoulder swap?

I checked and SmoothCam doesn't appear to be compatible with that particular feature in ‘Customizable Camera’, which uses a game script to edit the INI settings and just flips it to an opposite value on the x offset. It’s just a few lines of code I think.

I’ve noticed that being able to swap sides is HUGE in terms of playability when the camera is close. Even in vanilla. You don’t need a targeting system or anything that way.

So yeah if you add that, SmoothCam will reign supreme in every way imaginable!

**Comment by mwilsnd** [comment]
I went ahead and added this for you in beta 1. I also added an option to invert the X axis of the distance clamping setting when swapping shoulders, to cover the case where the X axis clamping range isn't even.
