### ISSUE TITLE
Interaction with Alternate Conversation Camera mod.

### ISSUE THREAD

**Issue by StoneColb** [mwilsnd/SkyrimSE-SmoothCam#2]
Not a problem with mod functionality, but rather a conflict with ACC's functionality.

ACC takes over camera settings during conversation, but it seems regardless of load order SmoothCam overwrites these settings and keeps the offsets as well as the zoom. So, in dialogue. this can potentially result in your character being partially off-screen or entirely off-screen if you have "Switch Targets" enabled in ACC.

I couldn't find a solution, so it's likely just an incompatibility.

**Comment by mwilsnd** [comment]
I'm looking in to a compatibility patch for this. This mod takes over near-total control of the third-person camera position so it really doesn't agree with other mods that manipulate the camera position without explicit patches.

**Comment by mwilsnd** [comment]
And this appears to be fixed now. I've added a new option to disable SmoothCam during dialog, allowing other mods like ACC to assume control without conflict. The next alpha should be published under the releases some time later today or tomorrow.

**Comment by StoneColb** [comment]
Yep. Tested, works perfectly. I have another suggestion as well, I'll open a new thread for that
