### ISSUE TITLE
Crash while using a bow

### ISSUE THREAD

**Issue by SirArlen** [mwilsnd/SkyrimSE-SmoothCam#22]
I crashed while fighting some bandits with a bow : https://pastebin.com/V1VJJvc3
Sorry for being vague but i can only repeat the crash by trying to kill some bandits with bow, melee and spells work fine

**Comment by mwilsnd** [comment]
I think I see where the issue might be, do you crash if you disable the 3D crosshair? Thanks for the debug trace, it really helps with issues like this.

**Comment by SirArlen** [comment]
Disable the 3D crosshair stopped the crash for me
