### ISSUE TITLE
What's AVx and OldCpu means? (Not an issue, just a question)

### ISSUE THREAD

**Issue by riskirills66** [mwilsnd/SkyrimSE-SmoothCam#27]
Can you be more specific?
Is it the x86 or x64 cpu?

**Comment by mwilsnd** [comment]
AVX is a specific set of instructions your processor may or may not be able to execute, Generally, processors made after 2011 should all be able to run AVX instructions. SmoothCam does a lot of matrix multiplication and vector math (which can be done faster using AVX) so being able to use AVX can provide a small performance gain - worth it if you have a million mods installed.

For people with older processors that don't support the AVX instruction set I publish a second version - OldCPU - which doesn't use it, so people can still use the mod.
