### ISSUE TITLE
Is it possible to decouple the orientation of the player from the camera?

### ISSUE THREAD

**Issue by JonnyWang33** [mwilsnd/SkyrimSE-SmoothCam#3]
Thank you so much for this! I am really hopeful you can solve the final hurdle of playing in 3rd person. At the end of the day, 3rd person is still entirely nauseating if you have to turn the camera in order to turn the player. The smooth cam is great, but it doesn't feel so smooth when the camera has to spin 180 degrees just to turn the player around. We have the mod "[360 walk and run plus](https://www.nexusmods.com/skyrim/mods/34508/?)" but this essentially replaced the strafe animations in order to make it look like the character is spinning. It doesn't work in combat, I assume because you would also need to rotate the hitboxes or else when the player is swinging towards the camera, the hitbox would still be directed away from the camera. I understand that this is not in the scope of your mod, but I think you are likely the community's best chance for a solution. Thank you for your work!

**Comment by mwilsnd** [comment]
Its something I'd like to try and do for sure. I'll need to figure out the player movement system which might take a while though. Consider it on the to-do list for the moment.

**Comment by alicealysia** [comment]
Honestly this would be an awesome feature, but damn... this mod looks like it was hell to code, my favorite function is ToddHowardTransform

**Comment by ghost** [comment]
@JonnyWang33 There's a mod that exists which brings such a feature to combat. [Combat Gameplay Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/33767) allows for 360 combat (toggled in the MCM). Unfortunately it only rotates the animations, and not the hitbox.

**Comment by mwilsnd** [comment]
With True Directional Movement out now, I don't see a reason to do this myself.
