### ISSUE TITLE
Suggestion: hotkey to switch between saved presets

### ISSUE THREAD

**Issue by ThisIsPatrick** [mwilsnd/SkyrimSE-SmoothCam#30]
Rather straightforward: a hotkey that can be set under the MCM Presets page that loads the next saved preset each time it's pressed. Empty presets would obviously be ignored.

A system to load an individual preset could also be added. Perhaps something using a modifier key (for example: Ctrl + Numpad 1-5.)

**Comment by mwilsnd** [comment]
Added a basic version of preset switching in 1.4, though I plan to come back to this and do a more proper version in the future.
