### ISSUE TITLE
Undeath (?) incompatibility - insanely high FOV

### ISSUE THREAD

**Issue by ReaperAnon** [mwilsnd/SkyrimSE-SmoothCam#31]
When transforming into a lich, even though I checked the text file with the bone and the bone seemed to have the correct name, the FOV gets insanely blown up.
Might be an Undeath specific thing, maybe something else. Could add a set of options as a fallback if that's the problem?

[https://i.imgur.com/cI4r3Fi.jpg](url)

**Comment by mwilsnd** [comment]
Thanks for reporting this, figured out what causes this issue and I'm adding a new Undeath compatibility option in the next version which should correct the issue.

**Comment by mwilsnd** [comment]
Fixed in 1.4
