### ISSUE TITLE
SKSE plugin load fails if non-ASCII chars are in SKSE/Plugins filename

### ISSUE THREAD

**Issue by SteveTownsend** [mwilsnd/SkyrimSE-SmoothCam#35]
As reported at Nexus in thread off of https://forums.nexusmods.com/index.php?showtopic=9191083/#entry87681073

TLDR : _std::filesystem::directory_iterator_ using _string()_ throws on non-ASCII chars. I hit this too :-(

See my mod logic for a working iteration using Unicode alternate:
https://github.com/SteveTownsend/SmartHarvestSE/blob/06266c2e0411ccde150594d0a500c032eb4d494b/src/Collections/CollectionManager.cpp#L364

Work round is to remove the file, which in my case is only there to test my own logic anyway.

**Comment by mwilsnd** [comment]
Thanks for reporting this, I was left scratching my head trying to figure out why the plugin wouldn't load for some people. I'm currently doing a somewhat major code refactor but I'll try and accelerate things so I can push a fix for this.

**Comment by SteveTownsend** [comment]
you're very welcome. I got so much help from users during testing of my mod that I feel obliged to help out when I can. I'll head back and endorse SmoothCam right now ;-)

**Comment by tr4wzified** [comment]
I think this is my issue aswell, was about to make a new issue for it. Will wait and see if the refactor's gonna help, thanks for your work! 

EDIT: actually made a new issue for it, don't think this is it unfortunately

**Comment by mwilsnd** [comment]
Better late than never, resolved in 1.4
