### ISSUE TITLE
My question about this mod

### ISSUE THREAD

**Issue by IsaacZM** [mwilsnd/SkyrimSE-SmoothCam#38]
You will have a version for LE users

**Comment by tr4wzified** [comment]
I'm pretty sure that would require a lot of work, SKSE plugins aren't easy to port over with all the changing memory addresses etc

**Comment by mwilsnd** [comment]
Yeah, I'm not really willing to invest such a large amount of time reverse engineering everything a second time. Sorry, but it will remain an SSE only mod for the foreseeable future.
