### ISSUE TITLE
Suggestion: Maximum camera movement range

### ISSUE THREAD

**Issue by StoneColb** [mwilsnd/SkyrimSE-SmoothCam#4]
So, something I'd like to see (though I'm unsure how doable it is) would be to limit how much the camera can move when you have the follow rate values really low. I like the slower camera speed at like 0.10, but the camera ends up being so far away from my character that it's hard to keep track of. 

What I'm suggesting is sort of like how in 3PCO there is a maximum range to the camera movement on the axes. Have the same thing here so that when I set my rate to, say 0.10, I'm not waiting for the camera to catch up to me, but I can still have the slower camera movement.

**Comment by mwilsnd** [comment]
After a little re-education on the subject of vector decomposition I've managed to get such a system up and running. You can now limit how far the camera is allowed to stray from its target position on each axis individually (X, Y, Z, minimum and maximum distance). There is still one other thing I'd like to get done before the next alpha so sit tight for the moment.

**Comment by mwilsnd** [comment]
Sorry for the delay, Alpha 1.2 is up now which includes new distance clamping options - give them a try and see if they do what you want.

**Comment by StoneColb** [comment]
Works great!

Found an unusual unrelated bug. I'll open another thread
