### ISSUE TITLE
While in third person, some bows shoot where the first person crosshair is.

### ISSUE THREAD

**Issue by rathoga** [mwilsnd/SkyrimSE-SmoothCam#40]
Whenever i'm using the Dragonbone bow, the arrow prediction in third person is accurate and always hits the target. However whenever I use the Nightingale bow the arrow misses and goes down and to the left. I've checked and it seems to fire the arrow where the first person crosshair is regardless of whether I am in third person or not.

**Comment by mwilsnd** [comment]
Currently the arrow prediction system has to make a few assumptions about how arrows act in the game. While this is usually fine, some mods can change certain properties that break those assumptions. I'm continuing my efforts in trying to remove as many of these assumptions as I can though. At the time of writing, the latest version (1.4) should improve things just a little bit more so feel free to give it a try.

**Comment by mwilsnd** [comment]
Should be fixed in 1.6, if not open a new issue
