### ISSUE TITLE
Add Support to Further Increase Crosshair Size

### ISSUE THREAD

**Issue by Matteas-Eden** [mwilsnd/SkyrimSE-SmoothCam#41]
Playing with the modification recently, I noticed that the dynamic ray-casted crosshair is quite small. Although there are some settings to increase the size, they either:
a) don't work
b) don't work as well as I would expect

With that in mind, I'd like to suggest adding further support to increase the crosshair size beyond the current available size.

**Comment by mwilsnd** [comment]
Added in 1.4
