### ISSUE TITLE
smoothcam issue

### ISSUE THREAD

**Issue by Iam-TheOverlord** [mwilsnd/SkyrimSE-SmoothCam#42]
**Can't activate anything** in this mod i reinstall and tested all the versions but the same i wish a fix for that
![Skyrim 27_01_2021 19_44_47](https://user-images.githubusercontent.com/49571757/106038376-2bdc6a80-60d8-11eb-84ae-08460d786802.png)
![Skyrim 27_01_2021 19_47_37](https://user-images.githubusercontent.com/49571757/106038729-955c7900-60d8-11eb-9edc-b91ed396745a.png)

**Comment by mwilsnd** [comment]
Try installing the latest version, most likely the plugin didn't load correctly for you. If the AVX version doesn't work, try the SSE version.
