### ISSUE TITLE
Feature Request - Toggle SmoothCam variable

### ISSUE THREAD

**Issue by weds4** [mwilsnd/SkyrimSE-SmoothCam#43]
Could you expose a variable to toggle SmoothCam? You could put it in the MCM so people can test something with the mod turned off or let people turn it off if they are in a situation they don't want it on for. In my case, I want to disable it during vampire lord form since I use another mod to manage 3rd person in that mode in ways that SmoothCam doesn't. It would be ideal if other mods could use their scripts to disable/enable SmoothCam situationally.

**Comment by mwilsnd** [comment]
Added in 1.4
