### ISSUE TITLE
Feature request - Camera height hotkey

### ISSUE THREAD

**Issue by BlueGunk** [mwilsnd/SkyrimSE-SmoothCam#44]
I use [Customizable Camera](https://www.nexusmods.com/skyrimspecialedition/mods/12201) which allows me to set a height by which I can drop the camera view and allocate it to a Hotkey. This is handy for certain...ahem...scenes. I hit 'L' and the 3rd person view drops from head height to my chosen two feet off the floor.

SmoothCam negates this adjustment (regardless of install / load order). So I cannot use it.

If SmoothCam had this feature, I could likely forget about using Customizable Camera.

Thanks for a great camera mod!

**Comment by mwilsnd** [comment]
Added in 1.4
