### ISSUE TITLE
Camera suddenly swapped

### ISSUE THREAD

**Issue by arudon** [mwilsnd/SkyrimSE-SmoothCam#45]
Hey, so I didn't touch anything really. I play with a Smoothcam preset, and hadn't touched anything before. Then, when I started playing today, the camera for some reason shifted everything to the left shoulder, instead of the right. It's like it was reading the +35 to go past the right shoulder, and was turning it into -35. And the weirdest thing is that it keeps disabling compatibility with Face-to-face conversation, which has never happened before. 

Again, I didn't change any mods or mess with the preset between play sessions. This just started happening

**Comment by mwilsnd** [comment]
You most likely have a key bound to the shoulder swap function, which does exactly what you are describing. If not, try assigning a key to it and seeing if it got triggered somehow.
