### ISSUE TITLE
SmoothCam and Simple Lock On Compatibility

### ISSUE THREAD

**Issue by DarkDragon777** [mwilsnd/SkyrimSE-SmoothCam#46]
This is a very simple question:

When I want to use Simple Lock On (the updated github version), I find that the bow control from SmoothCam are... well... not in the same way, while the Lock On crosshair sets the objetive in one direction, the projectile direction is in another one.

I was wondering if there is a way to patch this, or if there is something I'm doing wrong. I hope somebody could help me with this.

**Comment by mwilsnd** [comment]
I haven't been able to investigate this myself, compatibility with lock on mods isn't very high on my priority list at the current moment. You can always try the lock on feature in True Directional Movement which seems to work correctly. I'll close this for now but if I have some time in the future I'll look at a possible compatibility fix.
