### ISSUE TITLE
SkyHud not working

### ISSUE THREAD

**Issue by hexluminae** [mwilsnd/SkyrimSE-SmoothCam#5]
Essentially, running this completely brings back the vanilla heads up display, when I had a custom Dot crosshair and oblivion meters setup. That'd be fine, were it not for the A activate button floating over everything. I'm going to find out if there's a way to remove it myself, but I'd like to let you know that the raycast crosshair is a fine idea, but it really pulls me out of the experience when a big A in a circle and the word Activate are floating right above it. Just something visually weird about that.

I'll let you know if I can get them to go away with another mod! Thanks, it's absolutely wonderful otherwise, especially with a controller!

**Comment by derickso** [comment]
> For the raycasting 3D crosshair, SmoothCam replaces hudmenu.swf, meaning any other mod that changes the hud will likely have issues. (If you have issues but still want to use this mod you can simply omit hudmenu.swf when installing - the mod will still function, just without the 3D crosshair). Mod authors of conflicting mods can add support for the crosshair by adding a SetCrosshairPosition method inside hudmenu/HUDMenu.as (Refer to the changes I've made to hudmenu inside the UI folder).

From readme/main page
