### ISSUE TITLE
PiCho ENB causes smoothcam to crash

### ISSUE THREAD

**Issue by thantologist** [mwilsnd/SkyrimSE-SmoothCam#52]
PiCho ENB causes smoothcam to crash when saving enb settings in game, yes I know how absurd it sounds that an ENB can cause this, but I have tried and other ENBs does not cause this issue.

Attached is the crashdump, thank you!
[SmoothCam_AppCrash.zip](https://github.com/mwilsnd/SkyrimSE-SmoothCam/files/7090371/SmoothCam_AppCrash.zip)

**Comment by mwilsnd** [comment]
Well guess I learned something new - if you disable the crash dump handler and reload the game, does it still "crash"? Based on my findings, ENBSeries is using a windows API function to output a debug string which my crash handler thinks is an unhandled exception and enters the crash handler routine.

**Comment by mwilsnd** [comment]
Should be fixed in 1.6
