### ISSUE TITLE
CTD when dismounting from horse

### ISSUE THREAD

**Issue by OddDrifter** [mwilsnd/SkyrimSE-SmoothCam#54]
[.NetScriptFramework Crash Log](https://github.com/mwilsnd/SkyrimSE-SmoothCam/files/7124184/Crash_2021_9_7_15-53-29.txt)
[SmoothCam_AppCrash.zip](https://github.com/mwilsnd/SkyrimSE-SmoothCam/files/7124199/SmoothCam_AppCrash.zip)

Exactly as the title says. Whenever I dismount from a horse, the game crashes.

**Comment by mwilsnd** [comment]
I see the issue, thanks for reporting it. I'll have a fix in the next version - working on some new features and porting everything to commonlib so I won't be able to push a fix for this right away.

**Comment by mwilsnd** [comment]
Fixed in 1.6
