### ISSUE TITLE
Position offsets don't apply to idle/vanity camera

### ISSUE THREAD

**Issue by trumoose** [mwilsnd/SkyrimSE-SmoothCam#55]
The idle camera (the camera that rotates around the player after being inactive from the game for a certain amount of time) is absent from the mod controls -- which is a shame, because the positioning of the default camera isn't great, being focused on the player's head instead of the center of the body. In practice, that means the bottom part of the body is cut off. 

While the FOV slider in the "Standing" tab _does_ change the FOV value of the idle camera, the offsets do not. I tried all the offsets available, including the custom ones, but the camera returned to its default position when it idled. I'm curious if this can be changed or if it's hardcoded into the game -- if not, is it possible to have add a setting to this mod that circles around the player at a given speed, offset, and FOV?

**Comment by mwilsnd** [comment]
Corrected in 1.6 and added a new offset group for the vanity camera

**Comment by trumoose** [comment]
best devs ever. thanks a million
