### ISSUE TITLE
Can you separate camera following crosshair from camera following player?

### ISSUE THREAD

**Issue by Nickesponja** [mwilsnd/SkyrimSE-SmoothCam#6]
Well it's not like the camera follows the crosshair but you know, when you are standing, you move the camera, and this mod makes the camera pan in the opposite direction. Can you separate that effect from when the camera follows the character as they move? It's giving me a bit of motion sickness.

**Comment by mwilsnd** [comment]
In the latest release I've added a new group of options to control local-space (Like camera rotation) smoothing separately from the player position, take a look at those options and let me know how they work out for you. You can set the local-space smoothing rate to 1.0 which completely removes smoothing from camera rotations or turn it down to add some latency.
