### ISSUE TITLE
Crosshair re-enables itself in  3D Crosshair mode

### ISSUE THREAD

**Issue by cakeofhonor** [mwilsnd/SkyrimSE-SmoothCam#61]
If I wanted to turn off the regular crosshair completely using system settings, but still use the 3D crosshair to aim for magic and bows it doesn't work. The regular crosshair is off until aiming, then it stays on until turned off again (either by turning it off in the system menu again or switching to non-combat or melee combat mode with the no crosshair settings for those modes on in SmoothCam) .

**Comment by mwilsnd** [comment]
Should be fixed in 1.6.1.
