### ISSUE TITLE
Feature request: Hide crosshair when bow is not drawn

### ISSUE THREAD

**Issue by zax-ftw** [mwilsnd/SkyrimSE-SmoothCam#67]
Basically an complementary option to `HideCrosshairOutOfCombat` and `HideCrosshairMeleeCombat`. Crosshair would only appear when bow is drawn or when aiming with crossbow.

This feature, while being super immersive itself, it would also help hiding the crosshair position changes from real-raycasted to centered-in-middle-of-screen when shooting what can be quite annoying.

**Comment by mwilsnd** [comment]
Not exactly the same thing but give the new "Only Show Crosshair On Hit" and "3D Activator Crosshair" options a try.
