### ISSUE TITLE
SmoothCam warps Floating Healthbars in 3rd person

### ISSUE THREAD

**Issue by derickso** [mwilsnd/SkyrimSE-SmoothCam#7]
The healthbars will shift from above NPCs' heads to on the side of their heads depending on the angle to the player

**Comment by mwilsnd** [comment]
I've added a new patch to hopefully fix this issue, try enabling "Patch Projected HUD Elements" in the MCM with the latest release and then restart your game. If all is well, floating HUD elements should act correctly. While I'm not sure which health bar mod you are using, I assume it uses the same method as things like quest markers which this patch corrects.

**Comment by derickso** [comment]
Didn't work

![ScreenShot89](https://user-images.githubusercontent.com/6112623/81451158-b8a15b80-9138-11ea-9254-6fe7e64602d6.png)
![ScreenShot88](https://user-images.githubusercontent.com/6112623/81451180-c35bf080-9138-11ea-98e1-803e19249dbf.png)

There's only one Floating Healthbars mod

**Comment by derickso** [comment]
Seems to work now (forgot to restart game after enabling setting)
