### ISSUE TITLE
SmoothCam.dll disabled following recent update to Skyrim AE 1.6.640

### ISSUE THREAD

**Issue by Montep00** [mwilsnd/SkyrimSE-SmoothCam#71]
SmoothCam.dll disabled following recent update to Skyrim AE 1.6.640. The following error is given upon launch.

---------------------------
SKSE Plugin Loader
---------------------------
A DLL plugin has failed to load correctly. If a new version of Skyrim was just released, the plugin needs to be updated. Please check the mod's webpage for updates.
SmoothCam.dll: disabled, only compatible with versions earlier than 1.6.629
Continuing to load may result in lost save data or other undesired behavior.
Exit game? (yes highly suggested)
---------------------------
Yes   No   
---------------------------

**Comment by BrendanatorX** [comment]
Likewise, needs updating to match new Skyrim AE version, pls n thx can't wait <3

**Comment by mwilsnd** [comment]
Give this [preview release](https://github.com/mwilsnd/SkyrimSE-SmoothCam/releases/tag/Beta1.7-pre1) a try and let me know if there are any regressions.

**Comment by chonepieceyb** [comment]
> Give this [preview release](https://github.com/mwilsnd/SkyrimSE-SmoothCam/releases/tag/Beta1.7-pre1) a try and let me know if there are any regressions.

appreciate for the update release!

**Comment by BrendanatorX** [comment]
awesome, it's working, thanks!
