### ISSUE TITLE
SmoothCam incompatible with Alternate Conversation Camera witcher style dialog

### ISSUE THREAD

**Issue by derickso** [mwilsnd/SkyrimSE-SmoothCam#8]
Camera refuses to set the proper zoom level when talking to NPCs in third person with SmoothCam disabled during dialog, and enabled causes the camera offset to apply to player character when camera is on them, pushing them off the screen

**Comment by derickso** [comment]
Min follow distance for Following needs to be set to max (64)

**Comment by mwilsnd** [comment]
I wasn't able to replicate this issue, even when I set u3rdZoom in AlternateConversationCamera.ini to a high value to better visualize the zoom. If it all works for you then great, otherwise I'm not too sure what would be going on.
