### ISSUE TITLE
Can this project take advantage of Address Library for SKSE Plugins ?

### ISSUE THREAD

**Issue by distino** [mwilsnd/SkyrimSE-SmoothCam#9]
https://www.nexusmods.com/skyrimspecialedition/mods/32444

So that we're not forced to update to the latest version to use it? Thanks in advance.

**Comment by mwilsnd** [comment]
I've just added support for this in alpha 1.3, give it a try and let me know if it works for you. Note that I only offer active support for the latest version of the game/SKSE. That said, I've tested it on 1.5.8 and it appeared to work just fine.

**Comment by distino** [comment]
Hello! Thank you very much for your time you invested in making this possible. Just checked on 1.5.62 and it appears to be working.
